before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X main.version={{.Tag}} -X main.goversion=1.18
    main: ./cmd/switch
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "CHECKSUMS_SHA256_{{ toupper .ProjectName }}_{{ .Version }}.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
announce:
  twitter:
    enabled: false
    message_template: 'Hey "{{ .ProjectName }}" {{ .Tag }} is out! You can check it out at {{ .ReleaseURL }}!!'